export const RosterData = [
  {
    name: 'Jason Weiss',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/djjasonweiss',
    ig: 'https://instagram.com/djjasonweiss',
  },
  {
    name: 'Dr1ft',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/djdr1ft',
    ig: 'https://instagram.com/djdr1ft',
  },
  {
    name: 'Montone',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/djmontone',
    ig: 'https://instagram.com/djmontone',
  },
  {
    name: 'Mike Lowry',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/djmikelowry',
    ig: 'https://instagram.com/djmikelowry',
  },
  {
    name: 'Ryno',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/_djryno',
    ig: 'https://instagram.com/_djryno',
  },
  {
    name: 'Bad',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/badisgood',
    ig: 'https://instagram.com/badisgood',
  },
  {
    name: 'Fotsbeats',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/fotsbeats',
    ig: 'https://instagram.com/fotsbeats',
  },
  {
    name: 'Exodus',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/djexodus',
    ig: 'https://instagram.com/djexodus',
  },
  {
    name: 'Nick Spinelli',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/djnickspinelli',
    ig: 'https://instagram.com/djnickspinelli',
  },
  {
    name: 'Ernesto',
    img: '/assets/roster/default-dj.jpg',
    bio: 'This is a short blurb about the DJ',
    fb: 'https://facebook.com/djernesto1',
    ig: 'https://instagram.com/djernesto1',
  },
];
